#测试环境
server:
  port: ${SERVER_PORT:9220}

spring:
  application:
    name: rvc-detection-service
  config:
    import: classpath:you-cant-see-that.yml
  rabbitmq:
    host: ${RABBITMQ_HOST:ENC(GeHFmRZlNakxPyXWll4d/3YiEbwGKIxI)}
    port: ${RABBITMQ_PORT:15672}
    username: ${MQ_USERNAME:ENC(slkxj/szttzOZjcCB7BqDA==)}
    password: ${MQ_PASSWORD:ENC(lZidxgPqym5Wwxq4lf5//mH2tHIfg/XV3A4TQ0cSNNE=)}
    virtualHost: /



#阿里云ak
aliyun:
  secretId: ${ALIYUN_SID:ENC(5VkDvvVEoAbgREvmA4OcyxxoWcFCkmLEl1VilZsTmTDD4k+Hj/pnJQ==)}
  secretKey: ${ALIYUN_KEY:ENC(i0sSiBRWkVeSF9UFLz10nEztfXNoT8eNvRLNNB9zwSpYMXZip2aC7g==)}



