#测试环境
server:
  port: ${SERVER_PORT:9220}

spring:
  application:
    name: rvc-detection-service
  cloud:
    nacos:
      server-addr: ${NACOSADDR:ENC(mIQ9vQuo2M25EgeOZZwW4nYMACtogiyMHAI0Oh/Ypfc=)}
      username: ${NACOSUSERNAME:ENC(TbWnEnWk1SO/FFv/yPAH/A==)}
      password: ${NACOSPASSWORD:ENC(6ENawsNxgqHgbcrlhIQd+9rKWQl0Z+0G)}
      config:
        file-extension: yaml


  #  cloud:
#    nacos:
#      server-addr:
#      username:
#      password:
#      config:
#        file-extension: yaml
  config:
    import: classpath:you-cant-see-that.yml
  rabbitmq:
    host: ${RABBITMQ_HOST:ENC(yMFBFt6gkRargfjdfQRaLbQIj5k9HClY)}
    port: ${RABBITMQ_PORT:5672}
    username: ${MQ_USERNAME:ENC(KoxmBnemAL30cCxMbCvVdA==)}
    password: ${MQ_PASSWORD:ENC(bbi+chmzj/IqpNltm5VJxfRHVb767r2PppNXQsOHgVM=)}
    virtualHost: /


#阿里云ak
aliyun:
  secretId: ${ALIYUN_SID:ENC(5VkDvvVEoAbgREvmA4OcyxxoWcFCkmLEl1VilZsTmTDD4k+Hj/pnJQ==)}
  secretKey: ${ALIYUN_KEY:ENC(i0sSiBRWkVeSF9UFLz10nEztfXNoT8eNvRLNNB9zwSpYMXZip2aC7g==)}



