#测试环境
server:
  port: ${SERVER_PORT:9220}

spring:
  profiles:
    active: ${ACTIVE:prod}
  application:
    name: rvc-detection-service

  config:
    import: classpath:you-cant-see-that.yml

#阿里云ak
aliyun:
  secretId: ${ALIYUN_SID:ENC(5VkDvvVEoAbgREvmA4OcyxxoWcFCkmLEl1VilZsTmTDD4k+Hj/pnJQ==)}
  secretKey: ${ALIYUN_KEY:ENC(i0sSiBRWkVeSF9UFLz10nEztfXNoT8eNvRLNNB9zwSpYMXZip2aC7g==)}



